# fly.toml file generated for sniperbot-prod on 2023-04-12T20:21:24+10:00

app = "sniperbot-prod"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "syd"
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
